---
- name: reboot
  become: true
  reboot:
    post_reboot_delay: 15 # Seconds to wait after the reboot command was successful before attempting to validate the system rebooted successfully.
    reboot_timeout: 600 # Maximum seconds to wait for machine to reboot and respond to a test command.
